version: '3.7'
services:
  lametric_app:
    container_name: GST_LametricApp
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3095:3095"
    environment:
      - PORT=3095
    networks:
      - gst-tier

networks:
  gst-tier: